version: '4.25.2'

services:
  db:
    image: postgres:15.6-alpine3.19
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend: 
   image: wiltort/kruzhki-frontend:v1.0
   volumes:
     - ../frontend/:/app/result_build/
   depends_on:
      - db

  web:
    image: wiltort/kruzhki-react:v1.0
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      #- redoc:/app/api/docs/
    depends_on:
      - frontend
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  db_data:
  redoc: