# Generated by Django 3.2.6 on 2022-04-04 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0007_auto_20220404_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='Groups.Group', verbose_name='В списке у пользователей'),
        ),
    ]
