# Generated by Django 3.2.6 on 2022-04-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0010_auto_20220407_1941'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientsinGroup',
            constraint=models.UniqueConstraint(fields=('ingredient', 'Group'), name='unique_ingredient'),
        ),
    ]
