# Generated by Django 5.0.1 on 2024-02-18 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(verbose_name='Посещение')),
                ('is_passed', models.BooleanField(verbose_name='Зачет')),
                ('points', models.SmallIntegerField(blank=True, null=True, verbose_name='Оценка')),
            ],
        ),
        migrations.CreateModel(
            name='Joining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявления')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Время и дата')),
                ('topic', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название рубрики', max_length=150, verbose_name='Название')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение для рубрики', null=True, upload_to='rubric/', verbose_name='Изображение')),
                ('slug', models.SlugField(help_text='Введите слаг', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=2700))),
                ('begin_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stud_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите номер группы', max_length=50, unique=True, verbose_name='Номер')),
                ('title', models.CharField(help_text='Введите название курса', max_length=150, verbose_name='Название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='groups/')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('number_of_lessons', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Группа обучения',
                'verbose_name_plural': 'Группы обучения',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Обучающийся',
                'verbose_name_plural': 'Обучающиеся',
            },
        ),
    ]
