# Generated by Django 5.0.1 on 2024-02-18 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joining_to', to=settings.AUTH_USER_MODEL, verbose_name='Заявки на курсы'),
        ),
        migrations.AddField(
            model_name='attending',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='stud_group',
            name='rubric',
            field=models.ManyToManyField(db_index=True, related_name='stud_groups', to='courses.rubric', verbose_name='Рубрика'),
        ),
        migrations.AddField(
            model_name='stud_group',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='work_groups', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='courses.stud_group'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stud_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='courses.stud_group', verbose_name='Занятия'),
        ),
        migrations.AddField(
            model_name='joining',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='courses.stud_group', verbose_name='Заявки на курс'),
        ),
        migrations.AddField(
            model_name='student',
            name='in_group',
            field=models.ManyToManyField(related_name='students', to='courses.stud_group', verbose_name='Состоит в группе'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.PROTECT, related_name='study', to=settings.AUTH_USER_MODEL, verbose_name='Обучающийся'),
        ),
        migrations.AddField(
            model_name='attending',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attending', to='courses.student'),
        ),
        migrations.AddConstraint(
            model_name='joining',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_joining'),
        ),
    ]
