# Generated by Django 4.2.7 on 2023-11-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rubric_stud_group_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rubric/'),
        ),
    ]
