# Generated by Django 5.0.1 on 2024-02-25 09:36

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_attending_student_stud_group_students_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1, message='Номер урока начинается с 1')], verbose_name='Номер урока')),
                ('begin_at', models.TimeField(verbose_name='Начало урока')),
                ('end_at', models.TimeField(verbose_name='Конец урока')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ('number',),
            },
        ),
        migrations.AlterModelOptions(
            name='attending',
            options={'ordering': ('student',), 'verbose_name': 'Отметки', 'verbose_name_plural': 'Отметки'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('ldate',), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='stud_group',
            options={'ordering': ('begin_at',), 'verbose_name': 'Группа обучения', 'verbose_name_plural': 'Группы обучения'},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='date',
            new_name='ldate',
        ),
        migrations.AddField(
            model_name='stud_group',
            name='begin_at',
            field=models.DateField(db_index=True, default=datetime.date(2024, 2, 25), verbose_name='Начало обучения'),
        ),
        migrations.AlterField(
            model_name='attending',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Зачет'),
        ),
        migrations.AlterField(
            model_name='attending',
            name='is_present',
            field=models.BooleanField(default=True, verbose_name='Посещение'),
        ),
        migrations.AlterField(
            model_name='joining',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='joining_to', to=settings.AUTH_USER_MODEL, verbose_name='Заявки на курсы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='stud_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.stud_group', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(default='Введите тему урока', max_length=250),
        ),
        migrations.AlterField(
            model_name='stud_group',
            name='image',
            field=models.ImageField(default='../media/groups/1706241413450.jpeg', upload_to='groups/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='stud_group',
            name='number_of_lessons',
            field=models.SmallIntegerField(help_text='Введите количество часов', validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение: 1 час')], verbose_name='Количество часов'),
        ),
        migrations.CreateModel(
            name='Schedule_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='courses.stud_group', verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('btime', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='planned_lessons', to='courses.ring', verbose_name='Время урока')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.schedule_template', verbose_name='Шаблон')),
            ],
            options={
                'ordering': ('day_of_week', 'btime'),
            },
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddConstraint(
            model_name='schedule_item',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'btime'), name='unique_item'),
        ),
    ]
