# Generated by Django 4.2.7 on 2023-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_schedule_group_alter_stud_group_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='attending',
            name='points',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
