# Generated by Django 5.0.1 on 2024-02-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_ring_alter_attending_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule_item',
            options={'ordering': ('day_of_week', 'btime'), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='schedule_template',
            options={'ordering': ('group',), 'verbose_name': 'Недельное расписание', 'verbose_name_plural': 'Недельные расписания'},
        ),
    ]
