# Generated by Django 5.0.1 on 2024-03-05 12:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_schedule_item_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=250, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('-date',),
            },
        ),
        migrations.AlterModelOptions(
            name='attending',
            options={'ordering': ('student__last_name', 'student__first_name'), 'verbose_name': 'Отметки', 'verbose_name_plural': 'Отметки'},
        ),
        migrations.RemoveConstraint(
            model_name='schedule_item',
            name='unique_item',
        ),
        migrations.AlterField(
            model_name='attending',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending', to='courses.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(default='Введите тему урока', max_length=250, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='stud_group',
            name='begin_at',
            field=models.DateField(db_index=True, default=datetime.date(2024, 3, 5), verbose_name='Начало обучения'),
        ),
        migrations.AddConstraint(
            model_name='attending',
            constraint=models.UniqueConstraint(fields=('lesson', 'student'), name='unique_attending'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('stud_group', 'ldate'), name='un_lesson'),
        ),
        migrations.AddConstraint(
            model_name='schedule_item',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'btime', 'template'), name='unique_item'),
        ),
        migrations.AddConstraint(
            model_name='schedule_template',
            constraint=models.UniqueConstraint(fields=('group',), name='unique_schedule_template'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sended_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='message',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
    ]
