# Generated by Django 4.2.7 on 2023-11-26 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_attending_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_group',
            name='rubric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stud_groups', to='courses.rubric'),
            preserve_default=False,
        ),
    ]
