# Generated by Django 4.2.7 on 2024-01-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_stud_group_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group/'),
        ),
    ]
