# Generated by Django 5.0.1 on 2024-03-06 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_message_alter_attending_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_group',
            name='begin_at',
            field=models.DateField(db_index=True, default=datetime.date(2024, 3, 6), verbose_name='Начало обучения'),
        ),
    ]
