# Generated by Django 5.0.1 on 2024-02-11 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_stud_group_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AlterModelOptions(
            name='stud_group',
            options={'verbose_name': 'Группа обучения', 'verbose_name_plural': 'Группы обучения'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Обучающийся', 'verbose_name_plural': 'Обучающиеся'},
        ),
        migrations.AddField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(default='sport', help_text='Введите слаг', unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rubric',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для рубрики', null=True, upload_to='rubric/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, help_text='Введите название рубрики', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stud_group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/'),
        ),
        migrations.AlterField(
            model_name='stud_group',
            name='name',
            field=models.CharField(help_text='Введите номер группы', max_length=50, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='stud_group',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stud_groups', to='courses.rubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='stud_group',
            name='title',
            field=models.CharField(help_text='Введите название курса', max_length=150, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='student',
            name='in_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='courses.stud_group', verbose_name='Состоит в группе'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.PROTECT, related_name='study', to=settings.AUTH_USER_MODEL, verbose_name='Обучающийся'),
        ),
    ]
