# Generated by Django 5.0.1 on 2024-02-13 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_rubric_options_alter_stud_group_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='in_group',
        ),
        migrations.CreateModel(
            name='Joining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='courses.stud_group', verbose_name='Заявки на курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joining_to', to=settings.AUTH_USER_MODEL, verbose_name='Заявки на курсы')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='in_group',
            field=models.ManyToManyField(related_name='students', to='courses.stud_group', verbose_name='Состоит в группе'),
        ),
        migrations.AddConstraint(
            model_name='joining',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_joining'),
        ),
    ]
