# Generated by Django 5.0.1 on 2024-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_student_in_group_joining_student_in_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud_group',
            name='rubric',
        ),
        migrations.AddField(
            model_name='stud_group',
            name='rubric',
            field=models.ManyToManyField(db_index=True, related_name='stud_groups', to='courses.rubric', verbose_name='Рубрика'),
        ),
    ]
