# Generated by Django 3.2.6 on 2022-03-25 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_auto_20220322_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinGroup',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='Groups.ingredient', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='ingredientsinGroup',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_Group', to='Groups.Group', verbose_name='Ингредиент'),
        ),
    ]
